export const fieldMapping: Record<string, string> = {
  // Informations de base
  numeroDeDossierMdph: "Numero-dossier-MDPH",
  anneeScolaireDebut: "Annee-scolaire-debut",
  anneeScolaireFin: "Annee-scolaire-fin",
  dateReunionJour: "Date-reunion_Jour",
  dateReunionMois: "Date-reunion_Mois",
  dateReunionAnnee: "Date-reunion_Annee",

  // Élève
  nomEleve: "Nom-et-prenom-de-l-eleve",
  dateNaissanceJour: "Date-naissance_Jour",
  dateNaissanceMois: "Date-naissance_Mois",
  dateNaissanceAnnee: "Date-naissance_Annee",

  // Coordonnées élève
  numeroEtRue: "Numero-et-rue",
  ville: "Ville",
  codePostal: "Code-postal",
  telephone: "Tel",
  courriel: "Courriel",

  // Scolarité
  etablissementScolaire: "Etablissement-scolaire",
  classeFrequentee: "Classe-frequentee",
  adresseEtablissement: "Etablissement-scolaire_Numero-et-rue",
  villeEtablissement: "Etablissement-scolaire_Ville",
  codePostalEtablissement: "Points-saillants-scolarisation_Code-postal",

  // Enseignant
  enseignantNom: "Coordonnees-enseignant_Nom",
  enseignantTelephone: "Coordonnees-enseignant_Telephone",
  enseignantCourriel: "Coordonnees-enseignant_Courriel",

  // Plans et accompagnements
  pai: "PAI",
  planProjetsFormalisesCommentaires: "Plan-projets-formalises_Commentaires",
  mesuresEducatives: "Mesures-educatives",
  autresPlanOuProjetFormalises: "Autres-plan-ou-projet-formalises",
  rased: "RASED",
  accompagnementSoinsCommentaires: "Accompagnement-soins_Commentaires",
  sapad: "SAPAD",
  cned: "CNED",
  soinsHospitaliers: "Soins-hospitaliers",
  camps: "CAMPS",
  cmp: "CMP",
  cmpp: "CMPP",
  ems: "EMS",
  sessad: "SESSAD",
  soinsEnLiberal: "Soins-en-liberal",
  autresAccompagnementsEtSoins: "Autres-accompagnements-et-soins",

  // Aménagements pédagogiques
  amenagementsAdaptationsPedagogiques: "Amenagements-adaptations-pedagogiques",
  outilsCommunication: "Outils-communication",
  materielInformatiqueAudiovisuel: "Materiel-informatique-audiovisuel",
  materielDeficienceAuditive: "Materiel-deficience-auditive",
  materielDeficienceVisuelle: "Materiel-deficience-visuelle",
  mobilierEtPetitsMateriels: "Mobilier-et-petits-materiels",
  transport: "Transport",
  autresConditionsMaterielles: "Autres-coditions-materielles",

  // Horaires de scolarité
  lundiMatin: "Lundi-matin",
  lundiMidi: "Lundi-midi",
  lundiApresMidi: "Lundi-apres-midi",
  mardiMatin: "Mardi-matin",
  mardiMidi: "Mardi-midi",
  mardiApresMidi: "Mardi-apres-midi",
  mercrediMatin: "Mercredi-matin",
  mercrediMidi: "Mercredi-midi",
  mercrediApresMidi: "Mercredi-apres-midi",
  jeudiMatin: "Jeudi-matin",
  jeudiMidi: "Jeudi-midi",
  jeudiApresMidi: "Jeudi-apres-midi",
  vendrediMatin: "Vendredi-matin",
  vendrediMidi: "Vendredi-midi",
  vendrediApresMidi: "Vendredi-apres-midi",
  samediMatin: "Samedi-matin",

  // Capacités et besoins
  orientationDansLeTemps: "Orientation-dans-le-temps",
  orientationDansLespace: "Orientation-dans-l-espace",
  fixerSonAttention: "Fixer-son-attention",
  memoriser: "Memoriser",
  gererSaSecurite: "Gerer-sa-securite",
  respecterLesReglesDeVie: "Respecter-les-regles-de-vie",
  relationsAvecAutrui: "Relations-avec-autrui",
  maitriserSonComportement: "Maitriser-son-comportement",
  faireSesTransferts: "Faire-ses-transferts",
  accessibiliteDuBati: "Accessibilite-du-bati",
  seDeplacer: "Se-deplacer",
  utiliserLesTransportsCommuns: "Utiliser-les-transports-communs",
  activitesDeMotricite: "Activites-de-motricite",
  assurerElimination: "Assurer-l-elimination",
  shabillerSeDeshabiller: "S-habiller-se-deshabiller",
  prendreSesRepas: "Prendre-ses-repas",
  prendreSoinDeSaSante: "Prendre-soin-de-sa-sante",

  // Communication
  parler: "Parler",
  comprendreLaParole: "Comprendre-la-parole",
  comprendrePhraseSimple: "Comprendre-une-phrase-simple",
  messagesNonVerbaux: "Produire-recevoir-des-messages-non-verbaux",
  lire: "Lire",
  ecrire: "Ecrire",
  calculer: "Calculer",
  organiserSonTravail: "Organiser-son-travail",
  accepterDesConsignes: "Accepter-des-consignes",
  suivreDesConsignes: "Suivre-des-consignes",
  sinstallerDansLaClasse: "S-installer-dans-la-classe",
  utiliserSupportsPedagogiques: "Utiliser-des-supports-pedagogiques",
  utiliserMaterielAdapteHandicap: "Utiliser-du-materiel-adapte-a-son-handicap",
  prendreDesNotes: "Prendre-des-notes",
  participerSortiesScolaires: "Participer-a-des-sorties-scolaires",

  // Observations
  conditionsMateriellesCommentaires: "Conditions-materielles_Commentaires",
  niveauEnseignementApprentissages: "Niveau-d-enseignement-dans-les-apprentissages",
  controlerSonTravail: "Controler-son-travail",
  evolutionsObserveesPerspectives: "Evolutions-observées-et-persepectives-projet-professionnel",
  amenagementsAdaptationsPedagogiques2: "Amenagements-et-adaptations-pedagogiques",
  dispositifsCollectifsScolarisation: "Dispositifs-collectifs-de-scolarisation",
  missionsAideHumaine: "Missions-realisees-par-la-personne-chargee-de-l-aide-humaine",
  objectifsPedagogiquesAxes: "Objectifs-pedagogiques-et-axes-a-travailler-pour-suite-parcours",
  accompagnementEtSoins: "Accompagnement-et-soins",
  remarquesProfessionnels: "Remarques-des-professionnels",
  remarquesEleveParents: "Remarques-de-l-eleve-et-des-parents",
};